/**
 * RODLAB STUDIO — Schéma PostgreSQL embarqué (adapté depuis prisma db push)
 * Utilisé par src/lib/bootstrap.ts pour auto-créer la base si elle est absente,
 * afin que la connexion fonctionne même sans avoir lancé les scripts de setup.
 * Migré de SQLite vers PostgreSQL pour le déploiement sur Vercel (DATETIME →
 * TIMESTAMP(3), REAL → DOUBLE PRECISION). Régénération : adapter
 * scripts/gen-bootstrap-schema.py pour cibler PostgreSQL si le schéma change.
 */

export const SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE "Certificate" ( "id" TEXT NOT NULL PRIMARY KEY, "code" TEXT NOT NULL, "userId" TEXT NOT NULL, "courseId" TEXT NOT NULL, "enrollmentId" TEXT NOT NULL, "score" INTEGER NOT NULL, "holderName" TEXT NOT NULL, "issuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Certificate_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Certificate_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Certificate_enrollmentId_fkey" FOREIGN KEY ("enrollmentId") REFERENCES "Enrollment" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "Course" ( "id" TEXT NOT NULL PRIMARY KEY, "slug" TEXT NOT NULL, "title" TEXT NOT NULL, "subtitle" TEXT NOT NULL, "description" TEXT NOT NULL, "level" TEXT NOT NULL DEFAULT 'Débutant', "durationHours" INTEGER NOT NULL DEFAULT 14, "cover" TEXT, "published" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL )`,
  `CREATE TABLE "CourseModule" ( "id" TEXT NOT NULL PRIMARY KEY, "courseId" TEXT NOT NULL, "order" INTEGER NOT NULL, "title" TEXT NOT NULL, "summary" TEXT NOT NULL, "minutes" INTEGER NOT NULL DEFAULT 45, CONSTRAINT "CourseModule_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "Enrollment" ( "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "courseId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'ACTIVE', "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3), CONSTRAINT "Enrollment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Enrollment_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "Invoice" ( "id" TEXT NOT NULL PRIMARY KEY, "number" TEXT NOT NULL, "clientId" TEXT NOT NULL, "projectId" TEXT, "quoteId" TEXT, "amount" DOUBLE PRECISION NOT NULL DEFAULT 0, "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 18, "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0, "total" DOUBLE PRECISION NOT NULL DEFAULT 0, "currency" TEXT NOT NULL DEFAULT 'FCFA', "status" TEXT NOT NULL DEFAULT 'SENT', "method" TEXT, "notes" TEXT, "issueDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "dueDate" TIMESTAMP(3), "paidAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Invoice_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Invoice_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "Invoice_quoteId_fkey" FOREIGN KEY ("quoteId") REFERENCES "Quote" ("id") ON DELETE SET NULL ON UPDATE CASCADE )`,
  `CREATE TABLE "Lesson" ( "id" TEXT NOT NULL PRIMARY KEY, "moduleId" TEXT NOT NULL, "order" INTEGER NOT NULL, "title" TEXT NOT NULL, "minutes" INTEGER NOT NULL DEFAULT 12, "content" TEXT NOT NULL, CONSTRAINT "Lesson_moduleId_fkey" FOREIGN KEY ("moduleId") REFERENCES "CourseModule" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "LessonProgress" ( "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "lessonId" TEXT NOT NULL, "completedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "LessonProgress_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "LessonProgress_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "Lesson" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "LiveRegistration" ( "id" TEXT NOT NULL PRIMARY KEY, "sessionId" TEXT NOT NULL, "userId" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "country" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "LiveRegistration_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "LiveSession" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "LiveRegistration_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "LiveSession" ( "id" TEXT NOT NULL PRIMARY KEY, "slug" TEXT NOT NULL, "title" TEXT NOT NULL, "summary" TEXT NOT NULL, "description" TEXT NOT NULL, "platform" TEXT NOT NULL DEFAULT 'ZOOM', "joinUrl" TEXT, "embedUrl" TEXT, "startsAt" TIMESTAMP(3) NOT NULL, "durationMin" INTEGER NOT NULL DEFAULT 90, "status" TEXT NOT NULL DEFAULT 'SCHEDULED', "capacity" INTEGER NOT NULL DEFAULT 200, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL )`,
  `CREATE TABLE "Message" ( "id" TEXT NOT NULL PRIMARY KEY, "threadId" TEXT NOT NULL, "senderId" TEXT NOT NULL, "senderRole" TEXT NOT NULL, "content" TEXT NOT NULL, "type" TEXT NOT NULL DEFAULT 'TEXT', "audioDuration" INTEGER, "readAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Message_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "ChatPresence" ( "threadId" TEXT NOT NULL, "role" TEXT NOT NULL, "state" TEXT NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, PRIMARY KEY ("threadId", "role") )`,
  `CREATE TABLE "Notification" ( "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "url" TEXT, "readAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "Project" ( "id" TEXT NOT NULL PRIMARY KEY, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "serviceType" TEXT NOT NULL DEFAULT 'design-graphique', "status" TEXT NOT NULL DEFAULT 'PENDING', "progress" INTEGER NOT NULL DEFAULT 0, "budget" DOUBLE PRECISION, "currency" TEXT NOT NULL DEFAULT 'FCFA', "clientId" TEXT NOT NULL, "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "deadline" TIMESTAMP(3), "deliveredAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Project_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "ProjectTask" ( "id" TEXT NOT NULL PRIMARY KEY, "projectId" TEXT NOT NULL, "title" TEXT NOT NULL, "done" BOOLEAN NOT NULL DEFAULT false, "order" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "ProjectTask_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "PushSubscription" ( "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "endpoint" TEXT NOT NULL, "p256dh" TEXT NOT NULL, "auth" TEXT NOT NULL, "userAgent" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PushSubscription_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "Quiz" ( "id" TEXT NOT NULL PRIMARY KEY, "courseId" TEXT NOT NULL, "title" TEXT NOT NULL DEFAULT 'Examen final', "passScore" INTEGER NOT NULL DEFAULT 70, CONSTRAINT "Quiz_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "Course" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "QuizAttempt" ( "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "quizId" TEXT NOT NULL, "enrollmentId" TEXT NOT NULL, "answers" TEXT NOT NULL, "score" INTEGER NOT NULL, "correct" INTEGER NOT NULL, "total" INTEGER NOT NULL, "passed" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "QuizAttempt_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "QuizAttempt_quizId_fkey" FOREIGN KEY ("quizId") REFERENCES "Quiz" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "QuizAttempt_enrollmentId_fkey" FOREIGN KEY ("enrollmentId") REFERENCES "Enrollment" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "QuizQuestion" ( "id" TEXT NOT NULL PRIMARY KEY, "quizId" TEXT NOT NULL, "order" INTEGER NOT NULL, "prompt" TEXT NOT NULL, "options" TEXT NOT NULL, "answer" INTEGER NOT NULL, "explanation" TEXT, CONSTRAINT "QuizQuestion_quizId_fkey" FOREIGN KEY ("quizId") REFERENCES "Quiz" ("id") ON DELETE CASCADE ON UPDATE CASCADE )`,
  `CREATE TABLE "Quote" ( "id" TEXT NOT NULL PRIMARY KEY, "number" TEXT NOT NULL, "title" TEXT NOT NULL, "clientId" TEXT NOT NULL, "projectId" TEXT, "items" TEXT NOT NULL, "subtotal" DOUBLE PRECISION NOT NULL DEFAULT 0, "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 18, "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0, "total" DOUBLE PRECISION NOT NULL DEFAULT 0, "currency" TEXT NOT NULL DEFAULT 'FCFA', "status" TEXT NOT NULL DEFAULT 'DRAFT', "notes" TEXT, "validUntil" TIMESTAMP(3), "decidedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Quote_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Quote_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE SET NULL ON UPDATE CASCADE )`,
  `CREATE TABLE "QuoteRequest" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT, "company" TEXT, "serviceType" TEXT NOT NULL DEFAULT 'design-graphique', "budgetRange" TEXT, "message" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'NEW', "notes" TEXT, "convertedUserId" TEXT, "convertedProjectId" TEXT, "handledAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP )`,
  `CREATE TABLE "SiteContent" ( "id" TEXT NOT NULL PRIMARY KEY, "key" TEXT NOT NULL, "section" TEXT NOT NULL, "label" TEXT NOT NULL, "value" TEXT NOT NULL DEFAULT '', "type" TEXT NOT NULL DEFAULT 'TEXT', "updatedAt" TIMESTAMP(3) NOT NULL )`,
  `CREATE TABLE "TeamMember" ( "id" TEXT NOT NULL PRIMARY KEY, "ownerId" TEXT NOT NULL, "userId" TEXT, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT, "position" TEXT, "status" TEXT NOT NULL DEFAULT 'INVITED', "invitedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "joinedAt" TIMESTAMP(3), CONSTRAINT "TeamMember_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "TeamMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE )`,
  `CREATE TABLE "User" ( "id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'CLIENT', "phone" TEXT, "jobTitle" TEXT, "companyName" TEXT, "address" TEXT, "city" TEXT, "country" TEXT DEFAULT 'Togo', "avatarColor" TEXT NOT NULL DEFAULT '#bd4f2b', "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL )`,
  `CREATE UNIQUE INDEX "Certificate_code_key" ON "Certificate"("code")`,
  `CREATE UNIQUE INDEX "Certificate_enrollmentId_key" ON "Certificate"("enrollmentId")`,
  `CREATE UNIQUE INDEX "CourseModule_courseId_order_key" ON "CourseModule"("courseId", "order")`,
  `CREATE UNIQUE INDEX "Course_slug_key" ON "Course"("slug")`,
  `CREATE UNIQUE INDEX "Enrollment_userId_courseId_key" ON "Enrollment"("userId", "courseId")`,
  `CREATE UNIQUE INDEX "Invoice_number_key" ON "Invoice"("number")`,
  `CREATE UNIQUE INDEX "LessonProgress_userId_lessonId_key" ON "LessonProgress"("userId", "lessonId")`,
  `CREATE UNIQUE INDEX "Lesson_moduleId_order_key" ON "Lesson"("moduleId", "order")`,
  `CREATE UNIQUE INDEX "LiveRegistration_sessionId_userId_key" ON "LiveRegistration"("sessionId", "userId")`,
  `CREATE UNIQUE INDEX "LiveSession_slug_key" ON "LiveSession"("slug")`,
  `CREATE INDEX "Message_threadId_createdAt_idx" ON "Message"("threadId", "createdAt")`,
  `CREATE UNIQUE INDEX "PushSubscription_endpoint_key" ON "PushSubscription"("endpoint")`,
  `CREATE UNIQUE INDEX "QuizQuestion_quizId_order_key" ON "QuizQuestion"("quizId", "order")`,
  `CREATE UNIQUE INDEX "Quiz_courseId_key" ON "Quiz"("courseId")`,
  `CREATE UNIQUE INDEX "Quote_number_key" ON "Quote"("number")`,
  `CREATE UNIQUE INDEX "SiteContent_key_key" ON "SiteContent"("key")`,
  `CREATE UNIQUE INDEX "TeamMember_ownerId_email_key" ON "TeamMember"("ownerId", "email")`,
  `CREATE UNIQUE INDEX "TeamMember_userId_key" ON "TeamMember"("userId")`,
  `CREATE UNIQUE INDEX "User_email_key" ON "User"("email")`,
];
